# Generated by Django 4.2.30 on 2026-10-01 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_datasetrecord_data_quality_summary_and_more'),
        ('fraud', '0002_prediction_anomaly_score_prediction_decision_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(blank=True, db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('resolution', models.CharField(choices=[('UNRESOLVED', 'Unresolved / In Progress'), ('CONFIRMED_FRAUD', 'Confirmed Fraud (Ground Truth Positive)'), ('FALSE_POSITIVE', 'False Positive (Legitimate Transaction)'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity (SAR Filed / Account Monitored)'), ('NO_ISSUE_FOUND', 'No Issue Found'), ('INCONCLUSIVE', 'Inconclusive / Insufficient Evidence')], db_index=True, default='UNRESOLVED', max_length=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_system_generated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='alert_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='deduplication_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='rule_name',
            field=models.CharField(db_index=True, default='HIGH_RISK_THRESHOLD', max_length=100),
        ),
        migrations.AddField(
            model_name='fraudalert',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='inference_duration_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fraud.prediction'),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='HIGH', max_length=20),
        ),
        migrations.AlterField(
            model_name='fraudalert',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ACKNOWLEDGED', 'Acknowledged'), ('UNDER_REVIEW', 'Under Review'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='is_fraud',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='model_name',
            field=models.CharField(db_index=True, default='Random Forest Classifier', max_length=64),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='model_version',
            field=models.CharField(db_index=True, default='1.0.0', max_length=32),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='risk_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='prediction',
            name='risk_tier',
            field=models.CharField(db_index=True, default='LOW', max_length=20),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['status', 'severity'], name='fraud_fraud_status_f01be9_idx'),
        ),
        migrations.AddIndex(
            model_name='fraudalert',
            index=models.Index(fields=['assigned_to', 'status'], name='fraud_fraud_assigne_1bb2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model_name', 'model_version'], name='fraud_predi_model_n_53de8b_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['risk_tier', 'created_at'], name='fraud_predi_risk_ti_ff9d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['decision_state', 'created_at'], name='fraud_predi_decisio_838d5b_idx'),
        ),
        migrations.AddField(
            model_name='investigationnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationnote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fraud.investigationcase'),
        ),
        migrations.AddField(
            model_name='investigationcase',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='investigations', to='fraud.fraudalert'),
        ),
        migrations.AddField(
            model_name='investigationcase',
            name='assigned_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationcase',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationcase',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='investigations', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='evidenceattachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_attachments', to='fraud.investigationcase'),
        ),
        migrations.AddField(
            model_name='evidenceattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='investigationcase',
            index=models.Index(fields=['status', 'priority'], name='fraud_inves_status_55eae5_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationcase',
            index=models.Index(fields=['assigned_analyst', 'status'], name='fraud_inves_assigne_d7e75a_idx'),
        ),
        migrations.AddIndex(
            model_name='investigationcase',
            index=models.Index(fields=['resolution', 'closed_at'], name='fraud_inves_resolut_806eed_idx'),
        ),
    ]
