# Generated by Django 4.2.30 on 2026-10-01 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField()),
                ('total_records', models.IntegerField(default=0)),
                ('is_processed', models.BooleanField(default=False)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.IntegerField(default=1)),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Payment'), ('TRANSFER', 'Transfer'), ('CASH_OUT', 'Cash Out'), ('DEBIT', 'Debit'), ('CASH_IN', 'Cash In')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('name_orig', models.CharField(db_index=True, max_length=64)),
                ('old_balance_orig', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_balance_orig', models.DecimalField(decimal_places=2, max_digits=18)),
                ('name_dest', models.CharField(db_index=True, max_length=64)),
                ('old_balance_dest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('new_balance_dest', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_fraud_flag', models.BooleanField(default=False)),
                ('is_flagged_fraud', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.datasetrecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'amount'], name='transaction_transac_e6f9e3_idx'), models.Index(fields=['name_orig'], name='transaction_name_or_4ce83d_idx')],
            },
        ),
    ]
