# Generated by Django 4.2.30 on 2026-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrecord',
            name='data_quality_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasetrecord',
            name='failed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetrecord',
            name='processed_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.CharField(choices=[('ONLINE', 'Online Banking / Web'), ('MOBILE', 'Mobile Banking App'), ('ATM', 'Automated Teller Machine'), ('POS', 'Point of Sale'), ('WIRE', 'Wire Transfer Desk')], db_index=True, default='ONLINE', max_length=30),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_fraud_flag',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='step',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['name_dest'], name='transaction_name_de_22c3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at', 'transaction_type'], name='transaction_created_3dc431_idx'),
        ),
    ]
