# Generated by Django 3.2.25 on 2026-10-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_datasetrecord_data_quality_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_synthetic',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='latency_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='processing_status',
            field=models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='COMPLETED', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scenario_tag',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('SYNTHETIC', 'Synthetic Demo Stream'), ('INTERNAL', 'Internal Ledger'), ('EXTERNAL', 'External Ingested')], db_index=True, default='INTERNAL', max_length=20),
        ),
    ]
